### ISSUE TITLE
cannot run with cmd code in readme.md

### ISSUE THREAD

**Issue by name-used** [CosmoIknosLab/NuLite#2]
the inference code starts with `./cell_segmentation/inference/cell_detection.py` but no such python file in the project.
and the only file named with similar struct `./nuclei_detection/inference/nuclei_detection.py` has no main code.
if the true inference starting file is `./run_inference_wsi.py`, pls correct ur readme.

**Comment by duxuan11** [comment]
Same question. the script of run_interence_wsi.py reports '''
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/fastvit_s12.apple_in1k/resolve/main/model.safetensors (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))))"), '(Request ID: a9fd552a-49a6-4f32-9187-ef3b32fe1b8e)')
'''

**Comment by cristian921** [comment]
> the inference code starts with `./cell_segmentation/inference/cell_detection.py` but no such python file in the project. and the only file named with similar struct `./nuclei_detection/inference/nuclei_detection.py` has no main code. if the true inference starting file is `./run_inference_wsi.py`, pls correct ur readme.

I'm going to update the repository, thanks.

**Comment by cristian921** [comment]
> Same question. the script of run_interence_wsi.py reports ''' requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/fastvit_s12.apple_in1k/resolve/main/model.safetensors (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))))"), '(Request ID: a9fd552a-49a6-4f32-9187-ef3b32fe1b8e)') '''

Probably the problem is in timm package. I'll check soon.
